### ISSUE TITLE
Unzoom animation weird

### ISSUE THREAD

**Issue by asuri0n** [oblador/react-native-lightbox#105]
![svid_20180427_092936trim](https://user-images.githubusercontent.com/15729117/39350722-4ec8b988-49ff-11e8-902f-b03771f66297.gif)

Any ideas why it's doing that ?

**Comment by harrydema** [comment]
How did you solve it?

**Comment by asuri0n** [comment]
I used `renderContent`
`const renderFullImage = () => (
    <Image style={styles.imageZoom} resize="x300" resizeMode="contain" source={picture || defaultPicture} />
    )`

and for the Style : 
`  imageZoom: {
    borderRadius: Dimensions.get('window').height / 2,
    flex: 1,
    width: '100%',
    marginBottom: 15
  },`

The image need to be square

**Comment by rodrigobdz** [comment]
@asuri0n Could you provide a [MCVE](https://stackoverflow.com/help/mcve)?
I had the same problem when I set the width to a fixed value. I fixed it by using flex styles instead.
