### ISSUE TITLE
zoom after opened

### ISSUE THREAD

**Issue by kenphil** [oblador/react-native-lightbox#109]
How can I scale the image after opened the box

**Comment by peteroid** [comment]
You may wanna checkout this example https://github.com/oblador/react-native-lightbox/issues/5#issuecomment-222685485

pin-to-zoom is not yet supported and it would be supported in the v1!

**Comment by hanishcodebrew** [comment]
any update on this?

**Comment by aneeshcoddle** [comment]
any update ?
