### ISSUE TITLE
Remove touchableHighlight (black background)

### ISSUE THREAD

**Issue by nica0012** [oblador/react-native-lightbox#111]
Hello.

I have margin on my images so when I press on one an ugly black background shows up while pressing. How can I go about removing this?

Cheers.

**Comment by WestFR** [comment]
You can directly use `underlayColor={'transparent'}` on your Lightbox component !
Read doc or library file can help you without create a new issue.

So, this issue can be closed !

**Comment by ajaymarathe9** [comment]
> You can directly use `underlayColor={'transparent'}` on your Lightbox component !
> Read doc or library file can help you without create a new issue.
> 
> So, this issue can be closed !

Setting `underlayColor={'transparent'}` to TouchableHighlight resolving the issue Thanks.
`
  <TouchableHighlight
        underlayColor={'transparent'}
        onPress={() => this.TapToContinue()}
      >
        <View>
// Hello
        </View>
      </TouchableHighlight>
`

**Comment by kelly-draper-nutrien-com** [comment]
using TouchableOpacity instead of TouchableHighlight also works to get rid of the black background on press
