### ISSUE TITLE
This should be `this.props.onClose()`

### ISSUE THREAD

**Issue by ly9310** [oblador/react-native-lightbox#114]
https://github.com/oblador/react-native-lightbox/blob/4448979323623a56c62b5f8be1032322485cbd31/Lightbox.js#L112

**Comment by mccabemj** [comment]
@ly9310 no it shouldn't. The second parameter to `setState()` is an optional callback function. It's just referencing the function that `setState` will call. Its not meant to initiate the `onClose` function

**Comment by ly9310** [comment]
Emmmmm,I understand, Thanks for your reply.
