### ISSUE TITLE
RN for android can use this component？？？？

### ISSUE THREAD

**Issue by mvpdream** [oblador/react-native-lightbox#14]
The picture after clicking disappeared

**Comment by mvpdream** [comment]
The picture after clicking disappeared

**Comment by oblador** [comment]
Does the example project work for you?

**Comment by mvpdream** [comment]
no

**Comment by mvpdream** [comment]
can you help me？

**Comment by oblador** [comment]
I can help you, but you're not giving me anything to go on. Four question marks and one word replies aren't helping much. 

Basic functionality in Example works for me, but the one with carousel is buggy (an external component). My efforts right now are directed to a full refactor of this component (see [#navigator-refactor](https://github.com/oblador/react-native-lightbox/tree/navigator-refactor)) and I'm not likely to fix the Example just for android if the component itself is working.

**Comment by mvpdream** [comment]
There are some components of ios android can't use

**Comment by oblador** [comment]
This is not going anywhere.

**Comment by mvpdream** [comment]
For example:
![image](https://cloud.githubusercontent.com/assets/16203724/12439797/e44ca69e-bf6f-11e5-8895-6c0d6ca2d4c8.png)

**Comment by oblador** [comment]
All of those except StatusBarIOS and Modal are supported on android and both are soft dependencies.

**Comment by mvpdream** [comment]
Can you provide an example of android

**Comment by oblador** [comment]
https://github.com/oblador/react-native-lightbox/tree/master/Example

**Comment by mvpdream** [comment]
Okay, I try to find you again if you have any questions

**Comment by mvpdream** [comment]
![image](https://cloud.githubusercontent.com/assets/16203724/12442157/682486d6-bf88-11e5-9c14-01cc44954567.png)

**Comment by mvpdream** [comment]
ohh!!  now  Only these two places not normal Opens at the first place is is orange and then slide to see the pictures In the second place (just green, red part of the normal) a click no popup window directly into white
![image](https://cloud.githubusercontent.com/assets/16203724/12442452/053ed60e-bf8b-11e5-984b-c159ee5fb59e.png)

**Comment by oblador** [comment]
The second square uses Modal not available in android and the carousel itself is buggy in this demo.

**Comment by mvpdream** [comment]
Ok, why are the green point directly into white, also have no popup window
