### ISSUE TITLE
Is this module working?

### ISSUE THREAD

**Issue by ranyefet** [oblador/react-native-lightbox#21]
Hello,

I've just tried using this module with my app. I'm using RN v0.19

When I wrapped my ```<Image />``` with ```<Lightbox>``` I got a white space instead of the photo and nothing happen when i tap on it.

I just copied the example from the read me file.
Does it work with 0.19?

**Comment by oblador** [comment]
Are you on android?

**Comment by ranyefet** [comment]
No, on iOS.

**Comment by yamill** [comment]
I'm using RN v0.20 - when i wrap lightbox around my image and tap on it - the image disappears.

**Comment by oblador** [comment]
You probably need to set more style attributes. What code are you trying with?

**Comment by yamill** [comment]
@oblador ah ok gotcha. I didn't setup the style attributes. It's working now :+1: thanks!
