### ISSUE TITLE
use with NavigatorIOS problem

### ISSUE THREAD

**Issue by ChangJoo-Park** [oblador/react-native-lightbox#23]
Hello, 

NavigatorIOS has not getCurrentRoute(). so error when navigator={this.props.navigator}

**Comment by oblador** [comment]
Hi, `NavigatorIOS` is not supported (and can't be) just use the `Modal` fallback by simply not passing the `navigator` prop.

**Comment by ChangJoo-Park** [comment]
Thank you @oblador
