### ISSUE TITLE
Setting image to full width

### ISSUE THREAD

**Issue by labithiotis** [oblador/react-native-lightbox#25]
How can i set image to full width on open. I tried using activeProps but couldn't get that to work, I also tried to use callback for open but the effect was not disable as it just popped to width of device at end of animation.

https://dl.dropboxusercontent.com/u/2175584/Lightbox.mov

**Comment by oblador** [comment]
You need to update the style of your image in `activeProps` so that it's no longer fixed width.

**Comment by luisfuertes** [comment]
Can you give a example? I have problems to show image to full screen.

My component:
```
<View style={{flex: 1}}>
	<Lightbox
		navigator={this.props.navigator}
		activeProps={{alignItems: 'center', flex: 1,}}
	>
	        <Image
	          style={{ height: 180}}
		  resizeMode="cover"
	          source={require('../Resources/evento.png')}
	        />
      	</Lightbox>
</View>
```

And the results:
![captura de pantalla 2016-05-06 a las 12 15 59](https://cloud.githubusercontent.com/assets/18212615/15070442/83e77c70-1384-11e6-8143-1c2dc7c753a0.png)

![captura de pantalla 2016-05-06 a las 12 16 18](https://cloud.githubusercontent.com/assets/18212615/15070446/888ac8ae-1384-11e6-8f35-503ba1899623.png)

**Comment by martinezguillaume** [comment]
Add {{ flex: 1 }} to the image do the trick for me.
