### ISSUE TITLE
Make work with React Native Android

### ISSUE THREAD

**Issue by jamalneufeld** [oblador/react-native-lightbox#3]
Right now the `StatusBarIOS` throws an error, but when removed the animations don't show up on screen.

**Comment by oblador** [comment]
Hi, ATM React Native doesn't have the `Module` component on Android that this component depends upon. IMHO the latest release seems rushed to meet the famous "give us 6 months" quote.

**Comment by jamalneufeld** [comment]
Hmm, that's too bad. Thanks for looking into it.

**Comment by oblador** [comment]
Haven't seen any signs of `Modal` coming to android yet, so I've rewritten alot of the code to make it work with `Navigator` as well. Usage is slightly different, so see the README/example project. Grab [0.4.0](https://github.com/oblador/react-native-lightbox/releases/tag/v0.4.0) today ;-)
