### ISSUE TITLE
0.5.1 is a breaking upgrade from 0.5.0, please increment major or minor number instead of patch

### ISSUE THREAD

**Issue by javamonn** [oblador/react-native-lightbox#37]
0.5.1 introduced calls to the `StatusBar` API [here](https://github.com/oblador/react-native-lightbox/blob/master/LightboxOverlay.js#L112) and [here](https://github.com/oblador/react-native-lightbox/blob/master/LightboxOverlay.js#L130) which was introduced into RN with 0.20.0, effectively raising the minimum version required to run this module from 0.11.0 to 0.20.0.

This is a breaking change, and will break anyone using this module who is running RN < 0.20.0 and used the default `npm install --save react-native-lightbox`, as npm will install 0.5.1 automatically on the next install (e.g. on a CI machine) with the `^0.5.0` semvar check.

Please either increment your major number or minor number (following RN versioning schemes) instead of the patch number when you introduce breaking changes. Alternatively, you could wrap those StatusBar calls in RN version checks to make sure you have access to the API.

**Comment by oblador** [comment]
Fair point and I'll keep it in mind, but you should never rely on `package.json` for production dependencies; always use `npm shrinkwrap` which should solve your problem.

**Comment by javamonn** [comment]
hah, using `npm shrinkwrap` is also a very fair point. :)
