### ISSUE TITLE
Setting width and height on activeProps has no effect

### ISSUE THREAD

**Issue by greatwitenorth** [oblador/react-native-lightbox#38]
I have a thumbnail image in a list of items:
```
<Lightbox activeProps={{width: 300, height: 300}}>
    <Image style={{ width: 40, height: 40, marginRight: 5 }} source={{uri: this.props.image}}/>
</Lightbox>
```

When I click on the image, it just places the 40x40 image on a black background. My understanding was that setting a new width and height on activeProps should scale the image up. 

I'm using RN 0.22.2, and RN Lightbox 0.6.0

**Comment by Haiwen01** [comment]
I think you should do it like this:

`<Lightbox activeProps={{style: {width: 300, height: 300}}}>
    <Image style={{ width: 40, height: 40, marginRight: 5 }} source={{uri: this.props.image}}/>
</Lightbox>`

**Comment by luisfuertes** [comment]
It works for me:

```
      	<Lightbox
					navigator={this.props.navigator}
					activeProps={
						{
							style: {
								width: Dimensions.get('window').width,
								height: Dimensions.get('window').height
							},
							resizeMode: 'contain'
						}
					}
				>
	        <Image
	          style={{ height: 180}}
						resizeMode="cover"
	          source={require('../Resources/evento.png')}
	        />
      	</Lightbox>
```

**Comment by greatwitenorth** [comment]
Oh that makes sense now. Realized I wasn't putting my styles under the "styles" key.
