### ISSUE TITLE
Issue in Lightbox view iOS

### ISSUE THREAD

**Issue by adarshmuthappa** [oblador/react-native-lightbox#4]
Hey, first of all great work! 

I tried using it in my project but when I open an image/text in the lightbox view the second time it acts funny. Basically, the second time onwards, the image/text will open in the fullscreen mode at the position where it was closed the first time.

![gif lightbox](https://cloud.githubusercontent.com/assets/8210008/10415351/89131494-7013-11e5-8b80-652206209fdb.gif)

So then I installed 0.3.0 version and it works as it should. Looks like something changed from 0.3.0 to 0.4.0

**Comment by oblador** [comment]
Thanks for your bug report, this happens only when not using the new `Navigator` approach. Fixed in [0.4.1](https://github.com/oblador/react-native-lightbox/releases/tag/v0.4.1).

**Comment by adarshmuthappa** [comment]
Yup, just checked, its fixed now. Thanks for the quick response!
