### ISSUE TITLE
_this.props.navigator.getCurrentRoutes() is not a function 

### ISSUE THREAD

**Issue by iit2008047** [oblador/react-native-lightbox#45]
I am facing an issue with navigator. I see that to get the current route light box have used 
var routes = this.props.navigator.getCurrentRoutes();

but i see that this.props.navigato.navigationContext having CurrentRoute, am I missing something here
I am using NavigatorIOS and passing this.props.navigator

**Comment by oblador** [comment]
Hi, `NavigatorIOS` functionality is very limited and not supported by this library. Use `Navigator` instead.

**Comment by hielfx** [comment]
I would be nice to get it working with NavigationExperimental

**Comment by 77TecShaeer** [comment]
++
