### ISSUE TITLE
Modal onRequestClose warning

### ISSUE THREAD

**Issue by MingYe-dz** [oblador/react-native-lightbox#46]
onRequestClose Platform.OS === 'android' ? PropTypes.func.isRequired : PropTypes.func 

can you fix it?

**Comment by martinezguillaume** [comment]
same here
![image](https://cloud.githubusercontent.com/assets/17292331/16919477/1675c042-4d0a-11e6-9ce7-7acc53d00770.png)

**Comment by thanhnhan2tn** [comment]
i same here on react-native 0.3.0

**Comment by GCour** [comment]
I'm using the latest version but the fix hasn't been implemented yet.

I have manually added `onRequestClose={() => null}` on line 218 in LightboxOverlay.js and that's working

**Comment by sdrabb** [comment]
@GCour for me works, thanks a lot!!

**Comment by oblador** [comment]
Fixed in [0.7.0](https://github.com/oblador/react-native-lightbox/releases/tag/v0.7.0)

**Comment by joshuapinter** [comment]
Just for the record, I don't think `onRequestClose` should be a required prop. You can use Modals perfectly fine without passing a `onRequestClose` function.

**Comment by francyleo** [comment]
Add onRequestClose={() => {}} on Tag of you Modal!!!
