### ISSUE TITLE
Jumpy animation when closing

### ISSUE THREAD

**Issue by tylordippel** [oblador/react-native-lightbox#6]
Great module! It really makes it easy to add functionality to apps quickly. However, I was having one issue. I'm giving my image inside the lightbox a height and width of 200 and I want the image to take up the entire square, so I give it a resizeMode of 'cover'. But when you click on the image and the lightbox appears, I want the image to be as large as it can be without being cut off, so I used `activeProps={{resizeMode: 'contain'}}` so when the lightbox appears, you will see the entire image. It technically works; however, it's choppy. Basically, when you click on the image, the resizeMode changes right away, so the picture shrinks quickly before the lightbox appears. Then, when you close the lightbox, the image will shrink back down to it's original size, and then resizeMode will change after the animation, causing the same jumpy behavior. Is there any way to get around this / make the experience smoother.

Also, maybe even instead of that, would there be a way to make the lightbox simply fade away when closed instead shrinking back to it's original size. I did find the place in your code to make the change so the thumbnail won't disappear when the lightbox appears. And then, maybe if you swipe the lighbox down, the lightbox could just slide away (that's how the twitter app works now, at least on iOS). And if you click the close button, maybe the lightbox could just fade away without resizing?

**Comment by oblador** [comment]
Hi @tylordippel, 

In the current form you can use `Lightbox` with basically any element, but that makes it hard to do a perfect lightbox gallery which I guess is the most common use case. It's on my todo to make a gallery/carousel component specifically for images where I have more flexibility, I just need the time to do it. 

Fade in/out is not very elegant IMHO, and in that case you could just use  `Navigator` with a custom `sceneConfig` – no need for this component basically.

**Comment by tylordippel** [comment]
Got it! Thanks for the recommendation.
