### ISSUE TITLE
undefined is not a function (evaluating 'React.createClass')

### ISSUE THREAD

**Issue by Medardas** [oblador/react-native-lightbox#76]
Hello,
Im trying to run my app and seemingly without reason it started to throw this error"

`08-15 02:27:24.340 18745 18806 E ReactNativeJS: undefined is not a function (evaluating 'React.createClass')`
in LightboxOverlay.js

I did update PropTypes to be used from prop-types library since it doesn't seem to work with React.PropTypes anymore (this problem did show up in other node_modules, but prop-types lib seems to have fixed it) but other than that everything is how it supposed to be.

**EDIT**: Rewriting classes in ES6 seemed to have done the trick

**Comment by oblador** [comment]
Fixed in [0.7.0](https://github.com/oblador/react-native-lightbox/releases/tag/v0.7.0)
