### ISSUE TITLE
LightBox & BlurView

### ISSUE THREAD

**Issue by JonathanWi** [oblador/react-native-lightbox#9]
Hi!

When trying to apply a (Blurview)[https://github.com/Kureev/react-native-blur#installation] to an Image component inside a lightbox, I get the following error : 

````
Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Layout`
````

Any idea on why I can't apply blur on a Lightbox Image?

Cheers

EDIT: can we delete this? It appears that I was just using BlurView wrong: my bad!

**Comment by oblador** [comment]
Can't delete but I'll close :-)
